### ISSUE TITLE
Not working with the github username

### ISSUE THREAD

**Issue by rishichawda** [jrgarciadev/dev-cover#35]
I stumbled upon this project and thought to check it out. I put my GitHub username, but the site says, "Sorry, there is not enough information for the user rishichawda". Thought I should probably report it here.

**Comment by jrgarciadev** [comment]
Hi @rishichawda try again please, I already solved that 🙋🏻‍♂️

**Comment by rishichawda** [comment]
Don't think so. Took a screenshot this time thinking it would be helpful to you. Cheers! 😄 
![Screenshot 2021-03-08 at 8 42 19 PM](https://user-images.githubusercontent.com/26366288/110340062-d8522a80-804e-11eb-8dc0-dd1c921024df.png)

**Comment by jrgarciadev** [comment]
Hi @rishichawda, I can see your portfolio, try cleaning cache or open it in a private tab

<img width="1425" alt="Screen Shot 2021-03-08 at 12 17 55" src="https://user-images.githubusercontent.com/30373425/110340724-5212f580-8008-11eb-9a28-31f919885483.png">

**Comment by rishichawda** [comment]
Force reload worked. The first time I navigated to the page, since there was no cache whatsoever, it should have worked (unless you fixed something after opening the issue). Anyways, have a good one. Cheers!

**Comment by jrgarciadev** [comment]
Excellent! @rishichawda, yes I fixed the opened issue and closed it when I committed the solution. Thank you!!
