### ISSUE TITLE
How do I refresh the repos to be in sync with those pinned on github?

### ISSUE THREAD

**Issue by Andres-Andretti** [jrgarciadev/dev-cover#47]
The repos displayed on the portfolio don't reflect the most updated repos in my github after being deployed.

**Comment by jrgarciadev** [comment]
Hi Andres!, you just have to press on "Fetch GitHub repos" button.

![image](https://user-images.githubusercontent.com/30373425/123134425-2258f380-d427-11eb-97c9-7cb55670fe5f.jpeg)

**Comment by Andres-Andretti** [comment]
> Hi Andres!, you just have to press on "Fetch GitHub repos" button.
> 
> ![image](https://user-images.githubusercontent.com/30373425/123134425-2258f380-d427-11eb-97c9-7cb55670fe5f.jpeg)

Hey Junior. That option doesn't show up on mine ![image](https://user-images.githubusercontent.com/78054059/123181281-0a02cc00-d45b-11eb-89b8-d7babbbdec6f.jpeg)

**Comment by jrgarciadev** [comment]
Hey @Andres-Andretti, it's because that option is only available in [devcover.me](https://devcover.me), you must apply changes in your Devcover generated portfolio  [click here](https://devcover.me/portfolio/Andres-Andretti) and then redeploy on your Vercel account

Hope it helps you
